theme {
    # Appearance
    color_scheme = /usr/share/color-schemes/BreezeDark.colors
    icon_theme = Fluent-dark
    style = Darkly

    # Fonts
    font = Noto Sans
    font_size = 11

    font_fixed = Noto Sans
    font_fixed_size = 11
}

misc {
    # Interface behaviors
    single_click_activate = true
    menus_have_icons = true
    shortcuts_for_context_menus = true
}
