#!/usr/bin/env bash

BWHITE=$'\e[1;37m'
GREEN=$'\e[0;32m'
BLUE=$'\e[0;34m'
NC=$'\e[0m' # No Colour

echo "${GREEN}:: ${BWHITE}Regenerating ${GREEN}Booster${BWHITE} images...${NC}"
sudo /usr/lib/booster/regenerate_images

echo "${GREEN}:: ${BWHITE}Adding a ${GREEN}Limine${BWHITE} entry...${NC}"
sudo limine-entry-tool --add "booster-linux-cachyos" "/boot/booster-linux-cachyos.img" "/boot/vmlinuz-linux-cachyos"

ucode="amd-ucode.img"
b2sum=$(b2sum "/boot/$ucode" | cut -d' ' -f1)
if ! grep -q "$ucode#$b2sum" /boot/limine.conf; then
	echo "${GREEN}:: ${BWHITE}Adding ${BLUE}$ucode${BWHITE} to booster image...${NC}"
	sudo sed -i -e '/\/\/booster-linux-cachyos/,/cmdline:/ {' -e "/protocol:/ a \  module_path: boot():/$ucode#$b2sum" -e '}' /boot/limine.conf
fi
