#!/bin/env bash

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-~/.config}"

echo "Config home set to: $XDG_CONFIG_HOME"

# Check if there are any other monitors than eDP-1
if hyprctl monitors -j | jq -e 'any(.[]; .name != "eDP-1")'; then
	waybar -c "$XDG_CONFIG_HOME/waybar/config.jsonc"
else
	# Leave empty space for the bar
	hyprctl keyword workspace w[t1] m[0], gapsout:5 0 0 0
	hyprctl keyword workspace f[1] m[0], gapsout:5 0 0 0

	if acpi -a | grep -qi "off-line"; then
		waybar -c "$XDG_CONFIG_HOME/waybar/battery-config.jsonc"
	else
		waybar -c "$XDG_CONFIG_HOME/waybar/laptop-config.jsonc"
	fi
fi
