[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "medium"

[font.italic]
family = "JetBrainsMono NFM"

[font.bold_italic]
family = "JetBrainsMono NFM"

[window]
opacity = 0.8

[window.dimensions]
columns = 112
lines = 28

[window.padding]
x = 4
y = 2

# OneDark colors
[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x1e2127"
foreground = "0xabb2bf"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "Delete"
mods = "Control"
